#!/bin/bash
set -e
CONFIG_PATH=/data/options.json

DEFAULT_UUID=$(cat /proc/sys/kernel/random/uuid)
DEFAULT_HUBOT_SLACK_TOKEN=""
DEFAULT_HUBOT_HOME_ASSISTANT_HOST=""
DEFAULT_HUBOT_HOME_ASSISTANT_API_PASSWORD=""
DEFAULT_HUBOT_HOME_ASSISTANT_MONITOR_EVENTS="True"
DEFAULT_HUBOT_HOME_ASSISTANT_MONITOR_ALL_ENTITIES="True"
DEFAULT_HUBOT_HOME_ASSISTANT_EVENTS_DESTINATION="#home-assistant"

HUBOT_SLACK_TOKEN=$(jq --raw-output ".hubot_slack_token // empty" $CONFIG_PATH)
HUBOT_HOME_ASSISTANT_HOST=$(jq --raw-output ".hubot_home_assistant_host // empty" $CONFIG_PATH)
HUBOT_HOME_ASSISTANT_API_PASSWORD=$(jq --raw-output ".hubot_home_assistant_api_password // empty" $CONFIG_PATH)
HUBOT_HOME_ASSISTANT_MONITOR_EVENTS=$(jq --raw-output ".hubot_home_assistant_monitor_events // ${DEFAULT_HUBOT_HOME_ASSISTANT_MONITOR_EVENTS}" $CONFIG_PATH)
HUBOT_HOME_ASSISTANT_MONITOR_ALL_ENTITIES=$(jq --raw-output ".hubot_home_assistant_monitor_all_entities // ${DEFAULT_HUBOT_HOME_ASSISTANT_MONITOR_ALL_ENTITIES}" $CONFIG_PATH)
HUBOT_HOME_ASSISTANT_EVENTS_DESTINATION=$(jq --raw-output ".hubot_home_assistant_events_destination // ${DEFAULT_HUBOT_HOME_ASSISTANT_EVENTS_DESTINATION}" $CONFIG_PATH)

# Store generated UUID if not set
if [ -z "${UUID}" ]; then
  UUID=${DEFAULT_UUID^^}
  NEW_CONF=$(jq --arg uuid ${UUID} '. + {uuid: $uuid}' $CONFIG_PATH)
  echo "No UUID found, updating config with a generated UUID"
  echo $NEW_CONF
  echo $NEW_CONF > $CONFIG_PATH
fi

cd /hubot

yo hubot --owner="Hubot HomeAssistant" --name="Hubot" --adapter=slack
npm install hubot-home-assistant --save

HUBOT_SLACK_TOKEN=xoxb-384456159463-400870640661-hsw9RLXGXKv38Z3bnQT0ensI HUBOT_HOME_ASSISTANT_HOST="$HUBOT_HOME_ASSISTANT_HOST" HUBOT_HOME_ASSISTANT_API_PASSWORD=$HUBOT_HOME_ASSISTANT_API_PASSWORD HUBOT_HOME_ASSISTANT_MONITOR_EVENTS=$HUBOT_HOME_ASSISTANT_MONITOR_EVENTS HUBOT_HOME_ASSISTANT_MONITOR_ALL_ENTITIES=$HUBOT_HOME_ASSISTANT_MONITOR_ALL_ENTITIES HUBOT_HOME_ASSISTANT_EVENTS_DESTINATION="$HUBOT_HOME_ASSISTANT_EVENTS_DESTINATION" ./bin/hubot --adapter slack
