defaultEntryPoints = ["https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
##ACME_ENABLED    [entryPoints.http.redirect]
##ACME_ENABLED    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
  [entryPoints.dashboard]
    address = ":8080"
    compress = true

##ACME_ENABLED[acme]
##ACME_ENABLEDemail = "##ACME_EMAIL##"
##ACME_ENABLEDstorage = "/data/acme/acme.json"
##ACME_ENABLEDcaServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
##ACME_ENABLEDentryPoint = "https"
##ACME_ENABLED  [acme.httpChallenge]
##ACME_ENABLED  entryPoint = "http"
##ACME_ENABLEDonHostRule = true
##ACME_ENABLEDonDemand = true

##ACME_ENABLED[[acme.domains]]
##ACME_ENABLED  main = "##BASE_DOMAIN##"

[api]
entryPoint = "dashboard"
debug = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "##BASE_DOMAIN##"
watch = true
filename = "/docker.tmpl"
# templateVersion = 2
exposedByDefault = true
usebindportip = true
swarmMode = false

[file]

# Backends
[backends]

  [backends.homeassistant]

    [backends.homeassistant.servers]
      [backends.homeassistant.servers.server0]
        url = "http://homeassistant:8123/"
        weight = 1

# Frontends
[frontends]

  [frontends.homeassistant]
    entryPoints = ["http", "https"]
    backend = "homeassistant"
    passHostHeader = true

    [frontends.homeassistant.routes]
      [frontends.homeassistant.routes.route0]
        rule = "Host:##BASE_DOMAIN##"